/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Board.java
 *
 * Created on May 14, 2013, 5:19:06 PM
 */
package yatzee;

/**
 *
 * @author jllawsn
 */

import java.util.Random;
public class Board extends javax.swing.JFrame {

    /** Creates new form Board */
    public Board() {
        initComponents();
        myOne = 0;
        myTwo = 0;
        myThree = 0;
        myFour = 0;
        myFive = 0;
        
        
        //This sets the value of die number 1
        StringBuilder one = new StringBuilder();
        one.append("");
        one.append(myOne);
        String strOne = one.toString();
        dieOne.setText(strOne);
        
        //This sets the value of die number 2
        StringBuilder two = new StringBuilder();
        two.append("");
        two.append(myTwo);
        String strTwo= two.toString();
        dieTwo.setText(strTwo);
        
        //This sets the value of die number 3
        StringBuilder three = new StringBuilder();
        three.append("");
        three.append(myThree);
        String strThree = three.toString();
        dieThree.setText(strThree);
        
        //This sets the value of die number 4
        StringBuilder four = new StringBuilder();
        four.append("");
        four.append(myFour);
        String strFour = four.toString();
        dieFour.setText(strFour);
        
        //This sets  the value of die number 5
        StringBuilder five = new StringBuilder();
        five.append("");
        five.append(myFive);
        String strFive = five.toString();
        dieFive.setText(strFive);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dieOne = new javax.swing.JLabel();
        dieTwo = new javax.swing.JLabel();
        dieThree = new javax.swing.JLabel();
        dieFour = new javax.swing.JLabel();
        dieFive = new javax.swing.JLabel();
        keepOne = new java.awt.Checkbox();
        keepTwo = new java.awt.Checkbox();
        keepThree = new java.awt.Checkbox();
        keepFour = new java.awt.Checkbox();
        keepFive = new java.awt.Checkbox();
        jLabel6 = new javax.swing.JLabel();
        rollCount = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        roundsRemaining = new javax.swing.JLabel();
        rollDice = new javax.swing.JButton();
        setOne = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        setTwo = new javax.swing.JButton();
        setThree = new javax.swing.JButton();
        setFour = new javax.swing.JButton();
        setFive = new javax.swing.JButton();
        setSix = new javax.swing.JButton();
        setThreeOfAKind = new javax.swing.JButton();
        setFourOfAKind = new javax.swing.JButton();
        setFullHouse = new javax.swing.JButton();
        setSmallStraight = new javax.swing.JButton();
        setLargeStraight = new javax.swing.JButton();
        setYatzee = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        setChance = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        oneScore = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        twoScore = new javax.swing.JLabel();
        threeScore = new javax.swing.JLabel();
        fourScore = new javax.swing.JLabel();
        fiveScore = new javax.swing.JLabel();
        sixScore = new javax.swing.JLabel();
        threeOfAKindScore = new javax.swing.JLabel();
        fourOfAKindScore = new javax.swing.JLabel();
        fullHouseScore = new javax.swing.JLabel();
        smallStraightScore = new javax.swing.JLabel();
        largeStraightScore = new javax.swing.JLabel();
        yatzeeScore = new javax.swing.JLabel();
        chanceScore = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dieOne.setText("1");

        dieTwo.setText("2");

        dieThree.setText("3");

        dieFour.setText("4");

        dieFive.setText("5");

        keepOne.setLabel("keep");
        keepOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keepOneMouseClicked(evt);
            }
        });

        keepTwo.setLabel("keep");
        keepTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keepTwoMouseClicked(evt);
            }
        });

        keepThree.setLabel("keep");
        keepThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keepThreeMouseClicked(evt);
            }
        });

        keepFour.setLabel("keep");
        keepFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keepFourMouseClicked(evt);
            }
        });

        keepFive.setLabel("keep");
        keepFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keepFiveMouseClicked(evt);
            }
        });

        jLabel6.setText("Roll out of 3:");

        rollCount.setText("0");

        jLabel8.setText("Rounds Left:");

        roundsRemaining.setText("13");

        rollDice.setText("Roll Dice");
        rollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollDiceActionPerformed(evt);
            }
        });

        setOne.setText("Set Score");
        setOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setOneMouseClicked(evt);
            }
        });
        setOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOneActionPerformed(evt);
            }
        });

        jLabel1.setText("Ones");

        jLabel2.setText("Twos");

        jLabel3.setText("Threes");

        jLabel4.setText("Fours");

        jLabel5.setText("Fives");

        jLabel10.setText("Sixes");

        jLabel11.setText("3 of a kind");

        jLabel12.setText("4 of a kind");

        jLabel13.setText("Full House");

        jLabel14.setText("Small Straight");

        jLabel15.setText("Large Straight");

        jLabel16.setText("Yatzee (5 of a kind)");

        setTwo.setText("Set Score");
        setTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTwoActionPerformed(evt);
            }
        });

        setThree.setText("Set Score");
        setThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setThreeActionPerformed(evt);
            }
        });

        setFour.setText("Set Score");
        setFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFourActionPerformed(evt);
            }
        });

        setFive.setText("Set Score");
        setFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFiveActionPerformed(evt);
            }
        });

        setSix.setText("Set Score");
        setSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSixActionPerformed(evt);
            }
        });

        setThreeOfAKind.setText("Set Score");

        setFourOfAKind.setText("Set Score");

        setFullHouse.setText("Set Score");

        setSmallStraight.setText("Set Score");

        setLargeStraight.setText("Set Score");

        setYatzee.setText("Set Score");

        jLabel17.setText("Chance");

        setChance.setText("Set Score");

        jLabel18.setText("Upper Section:");

        oneScore.setText("0");

        jLabel20.setText("Score:");

        twoScore.setText("0");

        threeScore.setText("0");

        fourScore.setText("0");

        fiveScore.setText("0");

        sixScore.setText("0");

        threeOfAKindScore.setText("0");

        fourOfAKindScore.setText("0");

        fullHouseScore.setText("0");

        smallStraightScore.setText("0");

        largeStraightScore.setText("0");

        yatzeeScore.setText("0");

        chanceScore.setText("0");

        jLabel33.setText("Lower Section:");

        jLabel34.setText("Score:");

        jLabel35.setText("Dice:");

        jLabel7.setText("Total Score:");

        totalScore.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rollCount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundsRemaining))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addGap(124, 124, 124))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(dieOne, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(keepOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dieTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(keepTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dieThree, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(keepThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dieFour, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(keepFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(dieFive, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(keepFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(73, 73, 73)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(setThreeOfAKind)
                                                    .addComponent(setFourOfAKind)
                                                    .addComponent(setFullHouse)
                                                    .addComponent(setSmallStraight)
                                                    .addComponent(setLargeStraight)
                                                    .addComponent(setYatzee)
                                                    .addComponent(setChance)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(totalScore)
                                                    .addComponent(chanceScore)
                                                    .addComponent(yatzeeScore)
                                                    .addComponent(largeStraightScore)
                                                    .addComponent(smallStraightScore)
                                                    .addComponent(fullHouseScore)
                                                    .addComponent(fourOfAKindScore)
                                                    .addComponent(threeOfAKindScore)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel5))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(setSix)
                                            .addComponent(setFive)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(setOne)
                                                        .addComponent(setTwo)
                                                        .addComponent(setThree)
                                                        .addComponent(setFour))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fourScore)
                                                        .addComponent(threeScore)
                                                        .addComponent(twoScore)
                                                        .addComponent(oneScore)
                                                        .addComponent(fiveScore)
                                                        .addComponent(sixScore)))))))))
                        .addGap(278, 278, 278))
                    .addComponent(rollDice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rollCount)
                    .addComponent(roundsRemaining)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(setOne)
                                    .addComponent(oneScore)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(setTwo)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(setThree)
                                            .addComponent(threeScore)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(setFour)
                                            .addComponent(fourScore)
                                            .addComponent(jLabel4)))
                                    .addComponent(twoScore))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setFive)
                            .addComponent(fiveScore)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dieOne)
                            .addComponent(keepOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keepTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dieTwo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dieThree)
                            .addComponent(keepThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dieFour)
                            .addComponent(keepFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dieFive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(457, 457, 457)
                                        .addComponent(rollDice))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(setSix)
                                            .addComponent(jLabel10)
                                            .addComponent(sixScore))
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel34))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(setThreeOfAKind)
                                                    .addComponent(threeOfAKindScore))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(setFourOfAKind)
                                                    .addComponent(fourOfAKindScore)
                                                    .addComponent(jLabel12))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(setFullHouse)
                                                    .addComponent(fullHouseScore))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(setSmallStraight)
                                                    .addComponent(smallStraightScore)
                                                    .addComponent(jLabel14))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(setLargeStraight)
                                                    .addComponent(largeStraightScore)
                                                    .addComponent(jLabel15))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(yatzeeScore)
                                                    .addComponent(setYatzee)
                                                    .addComponent(jLabel16))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(setChance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel17))
                                                    .addComponent(chanceScore)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel13)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(totalScore)))))
                            .addComponent(keepFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollDiceActionPerformed
        
        if(rollNumber < 3){
            rollNumber++;
            
            //shows how many rolls the player has left in the round
            StringBuilder roll = new StringBuilder();
            roll.append("");
            roll.append(rollNumber);
            String strRoll = roll.toString();
            rollCount.setText(strRoll);

            Random dice = new Random();
            //These were placed incorrectly during earlier development
            //They need to be in the if statements down below to keep
            //from running if they're frozen
            //myOne = 1 + dice.nextInt(6);
            //myTwo = 1 + dice.nextInt(6);
            //myThree = 1 + dice.nextInt(6);
            //myFour = 1 + dice.nextInt(6);
            //myFive = 1 + dice.nextInt(6);
           

            if(!checkOne){
            //This sets the value of die number 1
            myOne = 1 + dice.nextInt(6);
            StringBuilder one = new StringBuilder();
            one.append("");
            one.append(myOne);
            String strOne = one.toString();
            dieOne.setText(strOne);
            }

            if(!checkTwo){
            //This sets the value of die number 2
            myTwo = 1 + dice.nextInt(6);
            StringBuilder two = new StringBuilder();
            two.append("");
            two.append(myTwo);
            String strTwo= two.toString();
            dieTwo.setText(strTwo);
            }

            if(!checkThree){
            //This sets the value of die number 3
            myThree = 1 + dice.nextInt(6);
            StringBuilder three = new StringBuilder();
            three.append("");
            three.append(myThree);
            String strThree = three.toString();
            dieThree.setText(strThree);
            }

            if(!checkFour){
            //This sets the value of die number 4
            myFour = 1 + dice.nextInt(6);
            StringBuilder four = new StringBuilder();
            four.append("");
            four.append(myFour);
            String strFour = four.toString();
            dieFour.setText(strFour);
            }

            if(!checkFive){
            //This sets  the value of die number 5
            myFive = 1 + dice.nextInt(6);
            StringBuilder five = new StringBuilder();
            five.append("");
            five.append(myFive);
            String strFive = five.toString();
            dieFive.setText(strFive);
            }
            
        }
    }//GEN-LAST:event_rollDiceActionPerformed

    private void keepOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keepOneMouseClicked
        // TODO add your handling code here:
        
        //freezes and unfreezes dice
        if(checkOne == false){
            checkOne = true;
        }else{
            checkOne = false;
        }    
    }//GEN-LAST:event_keepOneMouseClicked

    private void keepTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keepTwoMouseClicked
        // TODO add your handling code here:
        
        if(checkTwo == false){
            checkTwo = true;
        }else{
            checkTwo = false;
        }
        
    }//GEN-LAST:event_keepTwoMouseClicked

    private void keepThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keepThreeMouseClicked
        // TODO add your handling code here:
        if(checkThree == false){
            checkThree = true;
        }else{
            checkThree = false;
        }
    }//GEN-LAST:event_keepThreeMouseClicked

    private void keepFourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keepFourMouseClicked
        // TODO add your handling code here:
        if(checkFour == false){
            checkFour = true;
        }else{
            checkFour = false;
        }
    }//GEN-LAST:event_keepFourMouseClicked

    private void keepFiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keepFiveMouseClicked
        // TODO add your handling code here:
        if(checkFive == false){
            checkFive = true;
        }else{
            checkFive = false;
        }
    }//GEN-LAST:event_keepFiveMouseClicked

    private void setTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTwoActionPerformed
        // TODO add your handling code here:
        
        roundNumber -= 1;
        
        if(myOne == 2){
            myTwos += 2;
        }
        if(myTwo == 2){
           myTwos += 2;
        }
        if(myThree == 2){
            myTwos += 2;
        }
        if(myFour == 2){
            myTwos += 2;
        }
        if(myFive == 2){
            myTwos += 2;
        }
        
        overallScore += myTwos;
   
        StringBuilder settingTwo = new StringBuilder();
        settingTwo.append("");
        settingTwo.append(myTwos);
        String strTwo = settingTwo.toString();
        twoScore.setText(strTwo);
        
        StringBuilder addingScore = new StringBuilder();
        addingScore.append("");
        addingScore.append(overallScore);
        String theScore = addingScore.toString();
        totalScore.setText(theScore);
        
        StringBuilder subtractRound = new StringBuilder();
        subtractRound.append("");
        subtractRound.append(roundNumber);
        String minusRound = subtractRound.toString();
        roundsRemaining.setText(minusRound);
        
        //zeros everything out in preperation for the next round
        rollNumber = 0;
        myOne = 0;
        myTwo = 0;
        myThree = 0;
        myFour = 0;
        myFive = 0;
        
        StringBuilder roll = new StringBuilder();
        roll.append("");
        roll.append(rollNumber);
        String strRoll = roll.toString();
        rollCount.setText(strRoll);
        
        //This sets the value of die number 1
        StringBuilder one = new StringBuilder();
        one.append("");
        one.append(myOne);
        String strOne = one.toString();
        dieOne.setText(strOne);
        
        //This sets the value of die number 2
        StringBuilder otherTwo = new StringBuilder();
        otherTwo.append("");
        otherTwo.append(myTwo);
        String nextTwo= otherTwo.toString();
        dieTwo.setText(nextTwo);
        
        //This sets the value of die number 3
        StringBuilder three = new StringBuilder();
        three.append("");
        three.append(myThree);
        String strThree = three.toString();
        dieThree.setText(strThree);
        
        //This sets the value of die number 4
        StringBuilder four = new StringBuilder();
        four.append("");
        four.append(myFour);
        String strFour = four.toString();
        dieFour.setText(strFour);
        
        //This sets  the value of die number 5
        StringBuilder five = new StringBuilder();
        five.append("");
        five.append(myFive);
        String strFive = five.toString();
        dieFive.setText(strFive);
        
        /*If I were able to uncheck the checkboxes I would do that.
         * 
         * checkOne = false;
        checkTwo = false;
        checkThree = false;
        checkFour = false;
        checkFive = false;
         * 
         */
        
        
    }//GEN-LAST:event_setTwoActionPerformed

    private void setOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setOneMouseClicked
        // TODO add your handling code here:
        /*int temp = 0;
        for (int theNumber : myDice ){
            if(theNumber == 1){
                temp += 1;
            }
        }
        myOnes = temp;
        StringBuilder settingOne = new StringBuilder();
        settingOne.append("");
        settingOne.append(myOnes);
        String strOne = settingOne.toString();
        oneScore.setText(strOne);*/
    }//GEN-LAST:event_setOneMouseClicked

    private void setOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setOneActionPerformed
        // TODO add your handling code here:
        //for (int theNumber : myDice ){
            
            //System.out.println(theNumber);
            /*if(theNumber == 1){
                temp += theNumber;
            }*/
        //}
        
        roundNumber -= 1;
        if(myOne == 1){
            myOnes += 1;
        }
        if(myTwo == 1){
           myOnes += 1;
        }
        if(myThree == 1){
            myOnes += 1;
        }
        if(myFour == 1){
            myOnes += 1;
        }
        if(myFive == 1){
            myOnes += 1;
        }
        
        overallScore += myOnes;
        
   
        StringBuilder settingOne = new StringBuilder();
        settingOne.append("");
        settingOne.append(myOnes);
        String strOne = settingOne.toString();
        oneScore.setText(strOne);
        
        StringBuilder addingScore = new StringBuilder();
        addingScore.append("");
        addingScore.append(overallScore);
        String theScore = addingScore.toString();
        totalScore.setText(theScore);
        
        StringBuilder subtractRound = new StringBuilder();
        subtractRound.append("");
        subtractRound.append(roundNumber);
        String minusRound = subtractRound.toString();
        roundsRemaining.setText(minusRound);
        
        //zeros everything out in preperation for the next round
        rollNumber = 0;
        myOne = 0;
        myTwo = 0;
        myThree = 0;
        myFour = 0;
        myFive = 0;
        
        StringBuilder roll = new StringBuilder();
        roll.append("");
        roll.append(rollNumber);
        String strRoll = roll.toString();
        rollCount.setText(strRoll);
        
        //This sets the value of die number 1
        StringBuilder otherOne = new StringBuilder();
        otherOne.append("");
        otherOne.append(myOne);
        String nextOne = otherOne.toString();
        dieOne.setText(nextOne);
        
        //This sets the value of die number 2
        StringBuilder two = new StringBuilder();
        two.append("");
        two.append(myTwo);
        String strTwo= two.toString();
        dieTwo.setText(strTwo);
        
        //This sets the value of die number 3
        StringBuilder three = new StringBuilder();
        three.append("");
        three.append(myThree);
        String strThree = three.toString();
        dieThree.setText(strThree);
        
        //This sets the value of die number 4
        StringBuilder four = new StringBuilder();
        four.append("");
        four.append(myFour);
        String strFour = four.toString();
        dieFour.setText(strFour);
        
        //This sets  the value of die number 5
        StringBuilder five = new StringBuilder();
        five.append("");
        five.append(myFive);
        String strFive = five.toString();
        dieFive.setText(strFive);
        
    }//GEN-LAST:event_setOneActionPerformed

    private void setThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setThreeActionPerformed
        // TODO add your handling code here:
        roundNumber -= 1;
        
        if(myOne == 3){
            myThrees += 3;
        }
        if(myTwo == 3){
           myThrees += 3;
        }
        if(myThree == 3){
            myThrees += 3;
        }
        if(myFour == 3){
            myThrees += 3;
        }
        if(myFive == 3){
            myThrees += 3;
        }
        
        overallScore += myThrees;
        
   
        StringBuilder settingThree = new StringBuilder();
        settingThree.append("");
        settingThree.append(myThrees);
        String strThree = settingThree.toString();
        threeScore.setText(strThree);
        
        StringBuilder addingScore = new StringBuilder();
        addingScore.append("");
        addingScore.append(overallScore);
        String theScore = addingScore.toString();
        totalScore.setText(theScore);
        
        StringBuilder subtractRound = new StringBuilder();
        subtractRound.append("");
        subtractRound.append(roundNumber);
        String minusRound = subtractRound.toString();
        roundsRemaining.setText(minusRound);
        
        //zeros everything out in preperation for the next round
        rollNumber = 0;
        myOne = 0;
        myTwo = 0;
        myThree = 0;
        myFour = 0;
        myFive = 0;
        
        StringBuilder roll = new StringBuilder();
        roll.append("");
        roll.append(rollNumber);
        String strRoll = roll.toString();
        rollCount.setText(strRoll);
        
        //This sets the value of die number 1
        StringBuilder one = new StringBuilder();
        one.append("");
        one.append(myOne);
        String strOne = one.toString();
        dieOne.setText(strOne);
        
        //This sets the value of die number 2
        StringBuilder two = new StringBuilder();
        two.append("");
        two.append(myTwo);
        String strTwo= two.toString();
        dieTwo.setText(strTwo);
        
        //This sets the value of die number 3
        StringBuilder otherThree = new StringBuilder();
        otherThree.append("");
        otherThree.append(myThree);
        String nextThree = otherThree.toString();
        dieThree.setText(nextThree);
        
        //This sets the value of die number 4
        StringBuilder four = new StringBuilder();
        four.append("");
        four.append(myFour);
        String strFour = four.toString();
        dieFour.setText(strFour);
        
        //This sets  the value of die number 5
        StringBuilder five = new StringBuilder();
        five.append("");
        five.append(myFive);
        String strFive = five.toString();
        dieFive.setText(strFive);
    }//GEN-LAST:event_setThreeActionPerformed

    private void setFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setFourActionPerformed
        // TODO add your handling code here:
        roundNumber -= 1;
        
        if(myOne == 4){
            myFours += 4;
        }
        if(myTwo == 4){
           myFours += 4;
        }
        if(myThree == 4){
            myFours += 4;
        }
        if(myFour == 4){
            myFours += 4;
        }
        if(myFive == 4){
            myFours += 4;
        }
        
        overallScore += myFours;
        
   
        StringBuilder settingFour = new StringBuilder();
        settingFour.append("");
        settingFour.append(myFours);
        String strFour = settingFour.toString();
        fourScore.setText(strFour);
        
        StringBuilder addingScore = new StringBuilder();
        addingScore.append("");
        addingScore.append(overallScore);
        String theScore = addingScore.toString();
        totalScore.setText(theScore);
        
        StringBuilder subtractRound = new StringBuilder();
        subtractRound.append("");
        subtractRound.append(roundNumber);
        String minusRound = subtractRound.toString();
        roundsRemaining.setText(minusRound);
        
        //zeros everything out in preperation for the next round
        rollNumber = 0;
        myOne = 0;
        myTwo = 0;
        myThree = 0;
        myFour = 0;
        myFive = 0;
        
        StringBuilder roll = new StringBuilder();
        roll.append("");
        roll.append(rollNumber);
        String strRoll = roll.toString();
        rollCount.setText(strRoll);
        
        //This sets the value of die number 1
        StringBuilder one = new StringBuilder();
        one.append("");
        one.append(myOne);
        String strOne = one.toString();
        dieOne.setText(strOne);
        
        //This sets the value of die number 2
        StringBuilder two = new StringBuilder();
        two.append("");
        two.append(myTwo);
        String strTwo= two.toString();
        dieTwo.setText(strTwo);
        
        //This sets the value of die number 3
        StringBuilder three = new StringBuilder();
        three.append("");
        three.append(myThree);
        String strThree = three.toString();
        dieThree.setText(strThree);
        
        //This sets the value of die number 4
        StringBuilder otherFour = new StringBuilder();
        otherFour.append("");
        otherFour.append(myFour);
        String nextFour = otherFour.toString();
        dieFour.setText(nextFour);
        
        //This sets  the value of die number 5
        StringBuilder five = new StringBuilder();
        five.append("");
        five.append(myFive);
        String strFive = five.toString();
        dieFive.setText(strFive);
    }//GEN-LAST:event_setFourActionPerformed

    private void setFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setFiveActionPerformed
        // TODO add your handling code here:
        roundNumber -= 1;
        
        if(myOne == 5){
            myFives += 5;
        }
        if(myTwo == 5){
           myFives += 5;
        }
        if(myThree == 5){
            myFives += 5;
        }
        if(myFour == 5){
            myFives += 5;
        }
        if(myFive == 5){
            myFives += 5;
        }
        
        overallScore += myFives;
   
        StringBuilder settingFive = new StringBuilder();
        settingFive.append("");
        settingFive.append(myFives);
        String strFive = settingFive.toString();
        fiveScore.setText(strFive);
        
        StringBuilder addingScore = new StringBuilder();
        addingScore.append("");
        addingScore.append(overallScore);
        String theScore = addingScore.toString();
        totalScore.setText(theScore);
        
        StringBuilder subtractRound = new StringBuilder();
        subtractRound.append("");
        subtractRound.append(roundNumber);
        String minusRound = subtractRound.toString();
        roundsRemaining.setText(minusRound);
        
        //zeros everything out in preperation for the next round
        rollNumber = 0;
        myOne = 0;
        myTwo = 0;
        myThree = 0;
        myFour = 0;
        myFive = 0;
        
        StringBuilder roll = new StringBuilder();
        roll.append("");
        roll.append(rollNumber);
        String strRoll = roll.toString();
        rollCount.setText(strRoll);
        
        //This sets the value of die number 1
        StringBuilder one = new StringBuilder();
        one.append("");
        one.append(myOne);
        String strOne = one.toString();
        dieOne.setText(strOne);
        
        //This sets the value of die number 2
        StringBuilder two = new StringBuilder();
        two.append("");
        two.append(myTwo);
        String strTwo= two.toString();
        dieTwo.setText(strTwo);
        
        //This sets the value of die number 3
        StringBuilder three = new StringBuilder();
        three.append("");
        three.append(myThree);
        String strThree = three.toString();
        dieThree.setText(strThree);
        
        //This sets the value of die number 4
        StringBuilder four = new StringBuilder();
        four.append("");
        four.append(myFour);
        String strFour = four.toString();
        dieFour.setText(strFour);
        
        //This sets  the value of die number 5
        StringBuilder otherFive = new StringBuilder();
        otherFive.append("");
        otherFive.append(myFive);
        String nextFive = otherFive.toString();
        dieFive.setText(nextFive);
    }//GEN-LAST:event_setFiveActionPerformed

    private void setSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSixActionPerformed
        // TODO add your handling code here:
        roundNumber -= 1;
        
        if(myOne == 6){
            mySixes += 6;
        }
        if(myTwo == 6){
           mySixes += 6;
        }
        if(myThree == 6){
            mySixes += 6;
        }
        if(myFour == 6){
            mySixes += 6;
        }
        if(myFive == 6){
            mySixes += 6;
        }
        
        overallScore += mySixes;
        
   
        StringBuilder settingSix = new StringBuilder();
        settingSix.append("");
        settingSix.append(mySixes);
        String strSix = settingSix.toString();
        sixScore.setText(strSix);
        
        StringBuilder addingScore = new StringBuilder();
        addingScore.append("");
        addingScore.append(overallScore);
        String theScore = addingScore.toString();
        totalScore.setText(theScore);
        
        StringBuilder subtractRound = new StringBuilder();
        subtractRound.append("");
        subtractRound.append(roundNumber);
        String minusRound = subtractRound.toString();
        roundsRemaining.setText(minusRound);
        
        //resets the number of rolls to 0.
        rollNumber = 0;
        myOne = 0;
        myTwo = 0;
        myThree = 0;
        myFour = 0;
        myFive = 0;
        
        StringBuilder roll = new StringBuilder();
        roll.append("");
        roll.append(rollNumber);
        String strRoll = roll.toString();
        rollCount.setText(strRoll);
        
        //This sets the value of die number 1
        StringBuilder one = new StringBuilder();
        one.append("");
        one.append(myOne);
        String strOne = one.toString();
        dieOne.setText(strOne);
        
        //This sets the value of die number 2
        StringBuilder two = new StringBuilder();
        two.append("");
        two.append(myTwo);
        String strTwo= two.toString();
        dieTwo.setText(strTwo);
        
        //This sets the value of die number 3
        StringBuilder three = new StringBuilder();
        three.append("");
        three.append(myThree);
        String strThree = three.toString();
        dieThree.setText(strThree);
        
        //This sets the value of die number 4
        StringBuilder four = new StringBuilder();
        four.append("");
        four.append(myFour);
        String strFour = four.toString();
        dieFour.setText(strFour);
        
        //This sets  the value of die number 5
        StringBuilder five = new StringBuilder();
        five.append("");
        five.append(myFive);
        String strFive = five.toString();
        dieFive.setText(strFive);
    }//GEN-LAST:event_setSixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Board().setVisible(true);
            }
        });
    }
    int myOne ;
    int myTwo ;
    int myThree;
    int myFour;
    int myFive;
    
    int tempOne;
    int tempTwo;
    int tempThree;
    int tempFour;
    int tempFive;
    
    boolean checkOne = false;
    boolean checkTwo = false;
    boolean checkThree = false;
    boolean checkFour = false;
    boolean checkFive = false;
    
    int rollNumber = 0;
    int roundNumber = 13;
    int overallScore = 0;
    
    int[] myDice = {tempOne,tempTwo,tempThree,tempFour,tempFive};
    int myOnes;
    int myTwos;
    int myThrees;
    int myFours;
    int myFives;
    int mySixes;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chanceScore;
    private javax.swing.JLabel dieFive;
    private javax.swing.JLabel dieFour;
    private javax.swing.JLabel dieOne;
    private javax.swing.JLabel dieThree;
    private javax.swing.JLabel dieTwo;
    private javax.swing.JLabel fiveScore;
    private javax.swing.JLabel fourOfAKindScore;
    private javax.swing.JLabel fourScore;
    private javax.swing.JLabel fullHouseScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.Checkbox keepFive;
    private java.awt.Checkbox keepFour;
    private java.awt.Checkbox keepOne;
    private java.awt.Checkbox keepThree;
    private java.awt.Checkbox keepTwo;
    private javax.swing.JLabel largeStraightScore;
    private javax.swing.JLabel oneScore;
    private javax.swing.JLabel rollCount;
    private javax.swing.JButton rollDice;
    private javax.swing.JLabel roundsRemaining;
    private javax.swing.JButton setChance;
    private javax.swing.JButton setFive;
    private javax.swing.JButton setFour;
    private javax.swing.JButton setFourOfAKind;
    private javax.swing.JButton setFullHouse;
    private javax.swing.JButton setLargeStraight;
    private javax.swing.JButton setOne;
    private javax.swing.JButton setSix;
    private javax.swing.JButton setSmallStraight;
    private javax.swing.JButton setThree;
    private javax.swing.JButton setThreeOfAKind;
    private javax.swing.JButton setTwo;
    private javax.swing.JButton setYatzee;
    private javax.swing.JLabel sixScore;
    private javax.swing.JLabel smallStraightScore;
    private javax.swing.JLabel threeOfAKindScore;
    private javax.swing.JLabel threeScore;
    private javax.swing.JLabel totalScore;
    private javax.swing.JLabel twoScore;
    private javax.swing.JLabel yatzeeScore;
    // End of variables declaration//GEN-END:variables
}
