/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package homework4;

/**
 *
 * @author jllawsn
 */

import java.io.*;
public class Homework4InClass extends javax.swing.JFrame {

    /**
     * Creates new form Homework4InClass
     */
    
    public Homework4InClass() throws java.io.IOException {
        initComponents();
        
        //java.io.FileInputStream aFile = null;
        //FileInputStream aFile = null;
        //FileInputStream aFile;
        try{
            
        
        //Open the file prefs.cfg
        java.io.FileInputStream aFile = new java.io.FileInputStream("prefs.cfg");
        //aFile FileInputStream(String fileName) throws FileNotFoundException
        
        //Read in the first integer, which is the color
        java.util.Scanner fileScanner = new java.util.Scanner( aFile );
        picturePanel.setBackground(new java.awt.Color(fileScanner.nextInt()));
        //Read in the panel length and the panel width
        
        //Close the file
        }
        catch(java.io.IOException e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userColorCodeField = new javax.swing.JTextField();
        colorButtonActionPerformed = new javax.swing.JButton();
        picturePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sizeSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userColorCodeField.setText("jTextField1");
        userColorCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userColorCodeFieldActionPerformed(evt);
            }
        });

        colorButtonActionPerformed.setText("jButton1");
        colorButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformedActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("netapp2.divms.uiowa.edu\\jllawsn\\Documents\\My Pictures\\homework4pic.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout picturePanelLayout = new javax.swing.GroupLayout(picturePanel);
        picturePanel.setLayout(picturePanelLayout);
        picturePanelLayout.setHorizontalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePanelLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1093, Short.MAX_VALUE))
        );
        picturePanelLayout.setVerticalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(724, Short.MAX_VALUE))
        );

        sizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userColorCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorButtonActionPerformed)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(sizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(409, 409, 409)
                .addComponent(picturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(userColorCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(colorButtonActionPerformed)
                        .addGap(320, 320, 320)
                        .addComponent(sizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(1077, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(picturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformedActionPerformed
        // TODO add your handling code here:
        picturePanel.setBackground(new java.awt.Color(Integer.parseInt(userColorCodeField.getText())));
    }//GEN-LAST:event_colorButtonActionPerformedActionPerformed

    private void userColorCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userColorCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userColorCodeFieldActionPerformed

    private void sizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sizeSliderStateChanged
        // TODO add your handling code here:
        panelLength = 20 + sizeSlider.getValue();
        panelWidth = 20 + sizeSlider.getValue();
        picturePanel.setSize(panelLength, panelWidth);
    }//GEN-LAST:event_sizeSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws java.io.IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homework4InClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homework4InClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homework4InClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homework4InClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homework4InClass().setVisible(true);
            }
        });
    }
    private int panelLength, panelWidth;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorButtonActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel picturePanel;
    private javax.swing.JSlider sizeSlider;
    private javax.swing.JTextField userColorCodeField;
    // End of variables declaration//GEN-END:variables
}
